language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO=test_requirements/django-1.3.txt
    - DJANGO=test_requirements/django-1.4.txt
install:
    - pip install -q -r $DJANGO --use-mirrors
script:
    python runtests.py
notifications:
    email:
        recipients:
          - digi@treepy.com
        on_success: never
        on_failure: always
    irc:
        - "irc.freenode.org#django-cms"
        - "irc.freenode.org#django-cms-sprint"

